module.exports = {
  USER_ROLES: {
    CUSTOMER: 'CUSTOMER',
    AGENT: 'AGENT',
    ADMIN: 'ADMIN'
  },
  ORDER_STATUS: {
    CREATED: 'CREATED',
    ASSIGNED: 'ASSIGNED',
    PICKED_UP: 'PICKED_UP',
    IN_TRANSIT: 'IN_TRANSIT',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    FAILED: 'FAILED'
  },
  ORDER_TYPES: {
    B2B: 'B2B',
    B2C: 'B2C'
  },
  PAYMENT_TYPES: {
    PREPAID: 'PREPAID',
    COD: 'COD'
  },
  VOLUMETRIC_DIVISOR: 5000
};
